/apps/software/standard/core/miniforge/24.3.0-py3.11/bin/python
pyspark                  3.4.1
Game ID: 148, Move 0 processed...
Game ID: 148, Move 1 processed...
Game ID: 148, Move 2 processed...
Game ID: 148, Move 3 processed...
Game ID: 148, Move 4 processed...
Game ID: 148, Move 5 processed...
Game ID: 148, Move 6 processed...
Game ID: 148, Move 7 processed...
Game ID: 148, Move 8 processed...
Game ID: 148, Move 9 processed...
Traceback (most recent call last):
  File "/sfs/gpfs/tardis/home/zrc3hc/Chess/1. Preprocessing/transforming_chess_data.py", line 209, in <module>
    df_current = df_current.union(new_row)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apps/software/standard/core/spark/3.4.1/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 3665, in union
  File "/apps/software/standard/core/spark/3.4.1/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/apps/software/standard/core/spark/3.4.1/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 169, in deco
  File "/apps/software/standard/core/spark/3.4.1/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o6901.union.
: java.lang.OutOfMemoryError: Java heap space

